[tox]
envlist = py312, lint

[gh-actions]
python =
    3.12: py312, lint

[testenv]
allowlist_externals =
    pytest
skip_install = true
commands =
    pytest tests -n auto {posargs}

[testenv:lint]
allowlist_externals =
    ruff
    mypy
skip_install = true
commands =
    ruff check src tests {posargs}
    ruff format --check src tests
    mypy src tests
